spring:
  application:
    name: USER-SERVICE
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**
          filters:
            - name: CircuitBreaker
              args:
                name: Account-service
                fallbackUri: forward:/accountFallBack

        - id: user-service
          uri: lb://WALLET-SERVICE
          predicates:
            - Path=/wallet/**
          filters:
            - name: CircuitBreaker
              args:
                name: Wallet-service
                fallbackUri: forward:/walletFallBack
